export const initialUserData = Object.freeze({
  is_designer: 0,
  is_tailor: 0,
  is_seller: 0,
  email: "",
  short_bio: "",
  long_bio: "",
  first_name: "",
  last_name: "",
  gender: "",
  date_of_birth: "",
  address_line_1: "",
  address_line_2: "",
  city: "",
  province: "",
  postal_code: "",
  country: "",
  website: "",
  phone_number: "",
  secondary_email_address: "",
  facebook: "",
  twitter: "",
  instagram: "",
  linkedin: "",
  pinterest: "",
  behance: "",
  youtube: "",
});

export const initialDesignerData = Object.freeze({
  design_inspirations: "",
  design_process: "",
  areas_of_specialization: "",
  lead_time: "",
  pricing_structure: "",
});

export const initialUpdatePasswordData = Object.freeze({
  new_password: "",
  current_password: "",
  confirm_password: "",
});
export const initialChecklistData = {
  measurement_checklist: 1,
  upper_neck_circumference: "",
  lower_neck_circumference: "",
  chest_circumference: "",
  bust_circumference: "",
  under_bust_circumference: "",
  waist_circumference: "",
  mid_hip_circumference: "",
  hip_circumference: "",
  bust_distance: "",
  front_chest_width: "",
  back_chest_width: "",
  front_waist_length: "",
  back_waist_length: "",
  center_front_length: "",
  center_back_length: "",
  front_neck_depth: "",
  back_neck_depth: "",
  bust_depth: "",
  armhole_depth: "",
  bust_height: "",
  front_shoulder_width: "",
  back_shoulder_width: "",
  shoulder_length: "",
  shoulder_depth: "",
  elbow_circumference: "",
  underarm_length: "",
  sleeve_length: "",
  arm_circumference: "",
  wrist_circumference: "",
  elbow_length: "",
  armhole_circumference: "",
  sleeve_cap_height: "",
  hip_depth: "",
  crotch_depth: "",
  crotch_length: "",
  pants_length: "",
  knee_length: "",
  in_seam_length: "",
  thigh_circumference: "",
  mid_thigh_circumference: "",
  knee_circumference: "",
  calf_circumference: "",
  ankle_circumference: "",
  ankle_heel_circumference: "",
  body_height: "",
  body_length: "",
  side_seam: "",
  pants_trouser_length: "",
};

export const initialLatLon = Object.freeze({
  latitude: 0,
  longitude: 0,
});
