const CountryData = {
    AF: { name: 'Afghanistan', language: 'Pashto', currency: 'AFN', currencyCode: '؋' },
    AL: { name: 'Albania', language: 'Albanian', currency: 'ALL', currencyCode: 'L' },
    DZ: { name: 'Algeria', language: 'Arabic', currency: 'DZD', currencyCode: 'د.ج' },
    AS: { name: 'American Samoa', language: 'English', currency: 'USD', currencyCode: '$' },
    AD: { name: 'Andorra', language: 'Catalan', currency: 'EUR', currencyCode: '€' },
    AO: { name: 'Angola', language: 'Portuguese', currency: 'AOA', currencyCode: 'Kz' },
    AI: { name: 'Anguilla', language: 'English', currency: 'XCD', currencyCode: 'XCD$' },
    AG: { name: 'Antigua and Barbuda', language: 'English', currency: 'XCD', currencyCode: 'XCD$' },
    AR: { name: 'Argentina', language: 'Spanish', currency: 'ARS', currencyCode: 'ARS$' },
    AM: { name: 'Armenia', language: 'Armenian', currency: 'AMD', currencyCode: '֏' },
    AW: { name: 'Aruba', language: 'Dutch', currency: 'AWG', currencyCode: 'ƒ' },
    AU: { name: 'Australia', language: 'English', currency: 'AUD', currencyCode: 'AUD$' },
    AT: { name: 'Austria', language: 'German', currency: 'EUR', currencyCode: '€' },
    AZ: { name: 'Azerbaijan', language: 'Azerbaijani', currency: 'AZN', currencyCode: '₼' },
    BS: { name: 'Bahamas', language: 'English', currency: 'BSD', currencyCode: 'BSD$' },
    BH: { name: 'Bahrain', language: 'Arabic', currency: 'BHD', currencyCode: '.د.ب' },
    BD: { name: 'Bangladesh', language: 'Bengali', currency: 'BDT', currencyCode: '৳' },
    BB: { name: 'Barbados', language: 'English', currency: 'BBD', currencyCode: 'BBD$' },
    BY: { name: 'Belarus', language: 'Belarusian', currency: 'BYN', currencyCode: 'Br' },
    BE: { name: 'Belgium', language: 'Dutch', currency: 'EUR', currencyCode: '€' },
    BZ: { name: 'Belize', language: 'English', currency: 'BZD', currencyCode: 'BZD$' },
    BJ: { name: 'Benin', language: 'French', currency: 'XOF', currencyCode: 'CFA' },
    BM: { name: 'Bermuda', language: 'English', currency: 'BMD', currencyCode: 'BMD$' },
    BT: { name: 'Bhutan', language: 'Dzongkha', currency: 'BTN', currencyCode: 'Nu.' },
    BO: { name: 'Bolivia', language: 'Spanish', currency: 'BOB', currencyCode: 'Bs.' },
    BA: { name: 'Bosnia and Herzegovina', language: 'Bosnian', currency: 'BAM', currencyCode: 'KM' },
    BW: { name: 'Botswana', language: 'English', currency: 'BWP', currencyCode: 'P' },
    BR: { name: 'Brazil', language: 'Portuguese', currency: 'BRL', currencyCode: 'R$' },
    BN: { name: 'Brunei', language: 'Malay', currency: 'BND', currencyCode: 'BND$' },
    BG: { name: 'Bulgaria', language: 'Bulgarian', currency: 'BGN', currencyCode: 'лв' },
    BF: { name: 'Burkina Faso', language: 'French', currency: 'XOF', currencyCode: 'CFA' },
    BI: { name: 'Burundi', language: 'Kirundi', currency: 'BIF', currencyCode: 'FBu' },
    KH: { name: 'Cambodia', language: 'Khmer', currency: 'KHR', currencyCode: '៛' },
    CM: { name: 'Cameroon', language: 'French', currency: 'XAF', currencyCode: 'FCFA' },
    CA: { name: 'Canada', language: 'English', currency: 'CAD', currencyCode: 'CAD$' },
    CV: { name: 'Cape Verde', language: 'Portuguese', currency: 'CVE', currencyCode: 'Esc' },
    KY: { name: 'Cayman Islands', language: 'English', currency: 'KYD', currencyCode: 'KYD$' },
    CF: { name: 'Central African Republic', language: 'French', currency: 'XAF', currencyCode: 'FCFA' },
    TD: { name: 'Chad', language: 'French', currency: 'XAF', currencyCode: 'FCFA' },
    CL: { name: 'Chile', language: 'Spanish', currency: 'CLP', currencyCode: 'CLP$' },
    CN: { name: 'China', language: 'Mandarin', currency: 'CNY', currencyCode: '¥' },
    CO: { name: 'Colombia', language: 'Spanish', currency: 'COP', currencyCode: 'COP$' },
    KM: { name: 'Comoros', language: 'Comorian', currency: 'KMF', currencyCode: 'CF' },
    CG: { name: 'Congo', language: 'French', currency: 'XAF', currencyCode: 'FCFA' },
    CR: { name: 'Costa Rica', language: 'Spanish', currency: 'CRC', currencyCode: '₡' },
    HR: { name: 'Croatia', language: 'Croatian', currency: 'HRK', currencyCode: 'kn' },
    CU: { name: 'Cuba', language: 'Spanish', currency: 'CUP', currencyCode: '$' },
    CY: { name: 'Cyprus', language: 'Greek', currency: 'EUR', currencyCode: '€' },
    CZ: { name: 'Czechia', language: 'Czech', currency: 'CZK', currencyCode: 'Kč' },
    DK: { name: 'Denmark', language: 'Danish', currency: 'DKK', currencyCode: 'kr' },
    DJ: { name: 'Djibouti', language: 'French', currency: 'DJF', currencyCode: 'Fdj' },
    DM: { name: 'Dominica', language: 'English', currency: 'XCD', currencyCode: 'XCD$' },
    DO: { name: 'Dominican Republic', language: 'Spanish', currency: 'DOP', currencyCode: 'RD$' },
    EC: { name: 'Ecuador', language: 'Spanish', currency: 'USD', currencyCode: '$' },
    EG: { name: 'Egypt', language: 'Arabic', currency: 'EGP', currencyCode: '£' },
    SV: { name: 'El Salvador', language: 'Spanish', currency: 'USD', currencyCode: '$' },
    GQ: { name: 'Equatorial Guinea', language: 'Spanish', currency: 'XAF', currencyCode: 'FCFA' },
    ER: { name: 'Eritrea', language: 'Tigrinya', currency: 'ERN', currencyCode: 'Nkf' },
    EE: { name: 'Estonia', language: 'Estonian', currency: 'EUR', currencyCode: '€' },
    SZ: { name: 'Eswatini', language: 'Swazi', currency: 'SZL', currencyCode: 'E' },
    ET: { name: 'Ethiopia', language: 'Amharic', currency: 'ETB', currencyCode: 'Br' },
    FJ: { name: 'Fiji', language: 'English', currency: 'FJD', currencyCode: 'FJD$' },
    FI: { name: 'Finland', language: 'Finnish', currency: 'EUR', currencyCode: '€' },
    FR: { name: 'France', language: 'French', currency: 'EUR', currencyCode: '€' },
    GA: { name: 'Gabon', language: 'French', currency: 'XAF', currencyCode: 'FCFA' },
    GM: { name: 'Gambia', language: 'English', currency: 'GMD', currencyCode: 'D' },
    GE: { name: 'Georgia', language: 'Georgian', currency: 'GEL', currencyCode: '₾' },
    DE: { name: 'Germany', language: 'German', currency: 'EUR', currencyCode: '€' },
    GH: { name: 'Ghana', language: 'English', currency: 'GHS', currencyCode: '₵' },
    GR: { name: 'Greece', language: 'Greek', currency: 'EUR', currencyCode: '€' },
    GD: { name: 'Grenada', language: 'English', currency: 'XCD', currencyCode: 'XCD$' },
    GT: { name: 'Guatemala', language: 'Spanish', currency: 'GTQ', currencyCode: 'Q' },
    GN: { name: 'Guinea', language: 'French', currency: 'GNF', currencyCode: 'FG' },
    GW: { name: 'Guinea-Bissau', language: 'Portuguese', currency: 'XOF', currencyCode: 'CFA' },
    GY: { name: 'Guyana', language: 'English', currency: 'GYD', currencyCode: 'GYD$' },
    HT: { name: 'Haiti', language: 'French', currency: 'HTG', currencyCode: 'G' },
    HN: { name: 'Honduras', language: 'Spanish', currency: 'HNL', currencyCode: 'L' },
    HU: { name: 'Hungary', language: 'Hungarian', currency: 'HUF', currencyCode: 'Ft' },
    IS: { name: 'Iceland', language: 'Icelandic', currency: 'ISK', currencyCode: 'kr' },
    IN: { name: 'India', language: 'Hindi', currency: 'INR', currencyCode: '₹' },
    ID: { name: 'Indonesia', language: 'Indonesian', currency: 'IDR', currencyCode: 'Rp' },
    IR: { name: 'Iran', language: 'Persian', currency: 'IRR', currencyCode: '﷼' },
    IQ: { name: 'Iraq', language: 'Arabic', currency: 'IQD', currencyCode: 'ع.د' },
    IE: { name: 'Ireland', language: 'Irish', currency: 'EUR', currencyCode: '€' },
    IL: { name: 'Israel', language: 'Hebrew', currency: 'ILS', currencyCode: '₪' },
    IT: { name: 'Italy', language: 'Italian', currency: 'EUR', currencyCode: '€' },
    CI: { name: 'Ivory Coast', language: 'French', currency: 'XOF', currencyCode: 'CFA' },
    JM: { name: 'Jamaica', language: 'English', currency: 'JMD', currencyCode: 'JMD$' },
    JP: { name: 'Japan', language: 'Japanese', currency: 'JPY', currencyCode: '¥' },
    JO: { name: 'Jordan', language: 'Arabic', currency: 'JOD', currencyCode: 'JD' },
    KZ: { name: 'Kazakhstan', language: 'Kazakh', currency: 'KZT', currencyCode: '₸' },
    KE: { name: 'Kenya', language: 'Swahili', currency: 'KES', currencyCode: 'KSh' },
    KI: { name: 'Kiribati', language: 'English', currency: 'AUD', currencyCode: 'AUD$' },
    KP: { name: 'North Korea', language: 'Korean', currency: 'KPW', currencyCode: '₩' },
    KR: { name: 'South Korea', language: 'Korean', currency: 'KRW', currencyCode: '₩' },
    KW: { name: 'Kuwait', language: 'Arabic', currency: 'KWD', currencyCode: 'د.ك' },
    KG: { name: 'Kyrgyzstan', language: 'Kyrgyz', currency: 'KGS', currencyCode: 'сом' },
    LA: { name: 'Laos', language: 'Lao', currency: 'LAK', currencyCode: '₭' },
    LV: { name: 'Latvia', language: 'Latvian', currency: 'EUR', currencyCode: '€' },
    LB: { name: 'Lebanon', language: 'Arabic', currency: 'LBP', currencyCode: 'ل.ل' },
    LS: { name: 'Lesotho', language: 'Sotho', currency: 'LSL', currencyCode: 'L' },
    LR: { name: 'Liberia', language: 'English', currency: 'LRD', currencyCode: 'LRD$' },
    LY: { name: 'Libya', language: 'Arabic', currency: 'LYD', currencyCode: 'ل.د' },
    LI: { name: 'Liechtenstein', language: 'German', currency: 'CHF', currencyCode: 'CHF' },
    LT: { name: 'Lithuania', language: 'Lithuanian', currency: 'EUR', currencyCode: '€' },
    LU: { name: 'Luxembourg', language: 'Luxembourgish', currency: 'EUR', currencyCode: '€' },
    MG: { name: 'Madagascar', language: 'Malagasy', currency: 'MGA', currencyCode: 'Ar' },
    MW: { name: 'Malawi', language: 'Chichewa', currency: 'MWK', currencyCode: 'MK' },
    MY: { name: 'Malaysia', language: 'Malay', currency: 'MYR', currencyCode: 'RM' },
    MV: { name: 'Maldives', language: 'Dhivehi', currency: 'MVR', currencyCode: 'Rf' },
    ML: { name: 'Mali', language: 'French', currency: 'XOF', currencyCode: 'CFA' },
    MT: { name: 'Malta', language: 'Maltese', currency: 'EUR', currencyCode: '€' },
    MH: { name: 'Marshall Islands', language: 'Marshallese', currency: 'USD', currencyCode: '$' },
    MR: { name: 'Mauritania', language: 'Arabic', currency: 'MRU', currencyCode: 'UM' },
    MU: { name: 'Mauritius', language: 'English', currency: 'MUR', currencyCode: '₨' },
    MX: { name: 'Mexico', language: 'Spanish', currency: 'MXN', currencyCode: 'MX$' },
    FM: { name: 'Micronesia', language: 'English', currency: 'USD', currencyCode: '$' },
    MD: { name: 'Moldova', language: 'Romanian', currency: 'MDL', currencyCode: 'L' },
    MC: { name: 'Monaco', language: 'French', currency: 'EUR', currencyCode: '€' },
    MN: { name: 'Mongolia', language: 'Mongolian', currency: 'MNT', currencyCode: '₮' },
    ME: { name: 'Montenegro', language: 'Montenegrin', currency: 'EUR', currencyCode: '€' },
    MA: { name: 'Morocco', language: 'Arabic', currency: 'MAD', currencyCode: 'د.م.' },
    MZ: { name: 'Mozambique', language: 'Portuguese', currency: 'MZN', currencyCode: 'MT' },
    MM: { name: 'Myanmar', language: 'Burmese', currency: 'MMK', currencyCode: 'K' },
    NA: { name: 'Namibia', language: 'English', currency: 'NAD', currencyCode: 'NAD$' },
    NR: { name: 'Nauru', language: 'Nauruan', currency: 'AUD', currencyCode: 'AUD$' },
    NP: { name: 'Nepal', language: 'Nepali', currency: 'NPR', currencyCode: '₨' },
    NL: { name: 'Netherlands', language: 'Dutch', currency: 'EUR', currencyCode: '€' },
    NZ: { name: 'New Zealand', language: 'English', currency: 'NZD', currencyCode: 'NZ$' },
    NI: { name: 'Nicaragua', language: 'Spanish', currency: 'NIO', currencyCode: 'C$' },
    NE: { name: 'Niger', language: 'French', currency: 'XOF', currencyCode: 'CFA' },
    NG: { name: 'Nigeria', language: 'English', currency: 'NGN', currencyCode: '₦' },
    NO: { name: 'Norway', language: 'Norwegian', currency: 'NOK', currencyCode: 'kr' },
    OM: { name: 'Oman', language: 'Arabic', currency: 'OMR', currencyCode: 'ر.ع.' },
    PK: { name: 'Pakistan', language: 'Urdu', currency: 'PKR', currencyCode: '₨' },
    PW: { name: 'Palau', language: 'Palauan', currency: 'USD', currencyCode: '$' },
    PA: { name: 'Panama', language: 'Spanish', currency: 'PAB', currencyCode: 'B/.' },
    PG: { name: 'Papua New Guinea', language: 'English', currency: 'PGK', currencyCode: 'K' },
    PY: { name: 'Paraguay', language: 'Spanish', currency: 'PYG', currencyCode: '₲' },
    PE: { name: 'Peru', language: 'Spanish', currency: 'PEN', currencyCode: 'S/.' },
    PH: { name: 'Philippines', language: 'Filipino', currency: 'PHP', currencyCode: '₱' },
    PL: { name: 'Poland', language: 'Polish', currency: 'PLN', currencyCode: 'zł' },
    PT: { name: 'Portugal', language: 'Portuguese', currency: 'EUR', currencyCode: '€' },
    QA: { name: 'Qatar', language: 'Arabic', currency: 'QAR', currencyCode: 'ر.ق' },
    RO: { name: 'Romania', language: 'Romanian', currency: 'RON', currencyCode: 'lei' },
    RU: { name: 'Russia', language: 'Russian', currency: 'RUB', currencyCode: '₽' },
    RW: { name: 'Rwanda', language: 'Kinyarwanda', currency: 'RWF', currencyCode: 'FRw' },
    KN: { name: 'Saint Kitts and Nevis', language: 'English', currency: 'XCD', currencyCode: 'XCD$' },
    LC: { name: 'Saint Lucia', language: 'English', currency: 'XCD', currencyCode: 'XCD$' },
    VC: { name: 'Saint Vincent and the Grenadines', language: 'English', currency: 'XCD', currencyCode: 'XCD$' },
    WS: { name: 'Samoa', language: 'Samoan', currency: 'WST', currencyCode: 'WS$' },
    SM: { name: 'San Marino', language: 'Italian', currency: 'EUR', currencyCode: '€' },
    ST: { name: 'Sao Tome and Principe', language: 'Portuguese', currency: 'STN', currencyCode: 'Db' },
    SA: { name: 'Saudi Arabia', language: 'Arabic', currency: 'SAR', currencyCode: 'ر.س' },
    SN: { name: 'Senegal', language: 'French', currency: 'XOF', currencyCode: 'CFA' },
    RS: { name: 'Serbia', language: 'Serbian', currency: 'RSD', currencyCode: 'дин.' },
    SC: { name: 'Seychelles', language: 'Seychellois Creole', currency: 'SCR', currencyCode: '₨' },
    SL: { name: 'Sierra Leone', language: 'English', currency: 'SLL', currencyCode: 'Le' },
    SG: { name: 'Singapore', language: 'Malay', currency: 'SGD', currencyCode: 'SGD$' },
    SK: { name: 'Slovakia', language: 'Slovak', currency: 'EUR', currencyCode: '€' },
    SI: { name: 'Slovenia', language: 'Slovene', currency: 'EUR', currencyCode: '€' },
    SB: { name: 'Solomon Islands', language: 'English', currency: 'SBD', currencyCode: 'SBD$' },
    SO: { name: 'Somalia', language: 'Somali', currency: 'SOS', currencyCode: 'Sh.so.' },
    ZA: { name: 'South Africa', language: 'Zulu', currency: 'ZAR', currencyCode: 'R' },
    SS: { name: 'South Sudan', language: 'English', currency: 'SSP', currencyCode: '£' },
    ES: { name: 'Spain', language: 'Spanish', currency: 'EUR', currencyCode: '€' },
    LK: { name: 'Sri Lanka', language: 'Sinhala', currency: 'LKR', currencyCode: '₨' },
    SD: { name: 'Sudan', language: 'Arabic', currency: 'SDG', currencyCode: 'ج.س.' },
    SR: { name: 'Suriname', language: 'Dutch', currency: 'SRD', currencyCode: 'SRD$' },
    SE: { name: 'Sweden', language: 'Swedish', currency: 'SEK', currencyCode: 'kr' },
    CH: { name: 'Switzerland', language: 'German', currency: 'CHF', currencyCode: 'CHF' },
    SY: { name: 'Syria', language: 'Arabic', currency: 'SYP', currencyCode: '£' },
    TW: { name: 'Taiwan', language: 'Mandarin', currency: 'TWD', currencyCode: 'NT$' },
    TJ: { name: 'Tajikistan', language: 'Tajik', currency: 'TJS', currencyCode: 'ЅМ' },
    TZ: { name: 'Tanzania', language: 'Swahili', currency: 'TZS', currencyCode: 'TSh' },
    TH: { name: 'Thailand', language: 'Thai', currency: 'THB', currencyCode: '฿' },
    TL: { name: 'Timor-Leste', language: 'Portuguese', currency: 'USD', currencyCode: '$' },
    TG: { name: 'Togo', language: 'French', currency: 'XOF', currencyCode: 'CFA' },
    TO: { name: 'Tonga', language: 'Tongan', currency: 'TOP', currencyCode: 'T$' },
    TT: { name: 'Trinidad and Tobago', language: 'English', currency: 'TTD', currencyCode: 'TTD$' },
    TN: { name: 'Tunisia', language: 'Arabic', currency: 'TND', currencyCode: 'د.ت' },
    TR: { name: 'Turkey', language: 'Turkish', currency: 'TRY', currencyCode: '₺' },
    TM: { name: 'Turkmenistan', language: 'Turkmen', currency: 'TMT', currencyCode: 'm' },
    TV: { name: 'Tuvalu', language: 'Tuvaluan', currency: 'AUD', currencyCode: 'AUD$' },
    UG: { name: 'Uganda', language: 'English', currency: 'UGX', currencyCode: 'USh' },
    UA: { name: 'Ukraine', language: 'Ukrainian', currency: 'UAH', currencyCode: '₴' },
    AE: { name: 'United Arab Emirates', language: 'Arabic', currency: 'AED', currencyCode: 'د.إ' },
    GB: { name: 'United Kingdom', language: 'English', currency: 'GBP', currencyCode: '£' },
    US: { name: 'United States', language: 'English', currency: 'USD', currencyCode: '$' },
    UY: { name: 'Uruguay', language: 'Spanish', currency: 'UYU', currencyCode: '$U' },
    UZ: { name: 'Uzbekistan', language: 'Uzbek', currency: 'UZS', currencyCode: 'сўм' },
    VU: { name: 'Vanuatu', language: 'Bislama', currency: 'VUV', currencyCode: 'VT' },
    VE: { name: 'Venezuela', language: 'Spanish', currency: 'VES', currencyCode: 'Bs.' },
    VN: { name: 'Vietnam', language: 'Vietnamese', currency: 'VND', currencyCode: '₫' },
    YE: { name: 'Yemen', language: 'Arabic', currency: 'YER', currencyCode: '﷼' },
    ZM: { name: 'Zambia', language: 'English', currency: 'ZMW', currencyCode: 'ZK' },
    ZW: { name: 'Zimbabwe', language: 'English', currency: 'ZWL', currencyCode: 'Z$' },
};

export default CountryData;