const CountryData = {
    AF: { name: 'Afghanistan', language: 'Pashto', languageCode: 'ps', currency: 'AFN', currencyCode: '؋', rate: 78.74 },
    AL: { name: 'Albania', language: 'Albanian', languageCode: 'sq', currency: 'ALL', currencyCode: 'L', rate: 102.15 },
    DZ: { name: 'Algeria', language: 'Arabic', languageCode: 'ar', currency: 'DZD', currencyCode: 'د.ج', rate: 134.62 },
    AS: { name: 'American Samoa', language: 'English', languageCode: 'en', currency: 'USD', currencyCode: '$', rate: 1 },
    AD: { name: 'Andorra', language: 'Catalan', languageCode: 'ca', currency: 'EUR', currencyCode: '€', rate: 0.82 },
    AO: { name: 'Angola', language: 'Portuguese', languageCode: 'pt', currency: 'AOA', currencyCode: 'Kz', rate: 644.33 },
    AI: { name: 'Anguilla', language: 'English', languageCode: 'en', currency: 'XCD', currencyCode: 'XCD$', rate: 2.70 },
    AG: { name: 'Antigua and Barbuda', language: 'English', languageCode: 'en', currency: 'XCD', currencyCode: 'XCD$', rate: 2.70 },
    AR: { name: 'Argentina', language: 'Spanish', languageCode: 'es', currency: 'ARS', currencyCode: 'ARS$', rate: 100.08 },
    AM: { name: 'Armenia', language: 'Armenian', languageCode: 'hy', currency: 'AMD', currencyCode: '֏', rate: 487.47 },
    AW: { name: 'Aruba', language: 'Dutch', languageCode: 'nl', currency: 'AWG', currencyCode: 'ƒ', rate: 1.79 },
    AU: { name: 'Australia', language: 'English', languageCode: 'en', currency: 'AUD', currencyCode: 'AUD$', rate: 1.31 },
    AT: { name: 'Austria', language: 'German', languageCode: 'de', currency: 'EUR', currencyCode: '€', rate: 0.82 },
    AZ: { name: 'Azerbaijan', language: 'Azerbaijani', languageCode: 'az', currency: 'AZN', currencyCode: '₼', rate: 1.70 },
    BS: { name: 'Bahamas', language: 'English', languageCode: 'en', currency: 'BSD', currencyCode: 'BSD$', rate: 1 },
    BH: { name: 'Bahrain', language: 'Arabic', languageCode: 'ar', currency: 'BHD', currencyCode: '.د.ب', rate: 0.38 },
    BD: { name: 'Bangladesh', language: 'Bengali', languageCode: 'bn', currency: 'BDT', currencyCode: '৳', rate: 84.89 },
    BB: { name: 'Barbados', language: 'English', languageCode: 'en', currency: 'BBD', currencyCode: 'BBD$', rate: 2 },
    // BY: { name: 'Belarus', language: 'Belarusian', languageCode: 'be', currency: 'BYN', currencyCode: 'Br', rate: 2.55 },
    BE: { name: 'Belgium', language: 'Dutch', languageCode: 'nl', currency: 'EUR', currencyCode: '€', rate: 0.82 },
    BZ: { name: 'Belize', language: 'English', languageCode: 'en', currency: 'BZD', currencyCode: 'BZD$', rate: 2 },
    BJ: { name: 'Benin', language: 'French', languageCode: 'fr', currency: 'XOF', currencyCode: 'CFA', rate: 577.93 },
    BM: { name: 'Bermuda', language: 'English', languageCode: 'en', currency: 'BMD', currencyCode: 'BMD$', rate: 1 },
    BT: { name: 'Bhutan', language: 'Dzongkha', languageCode: 'dz', currency: 'BTN', currencyCode: 'Nu.', rate: 74.77 },
    BO: { name: 'Bolivia', language: 'Spanish', languageCode: 'es', currency: 'BOB', currencyCode: 'Bs.', rate: 6.90 },
    BA: { name: 'Bosnia and Herzegovina', language: 'Bosnian', languageCode: 'bs', currency: 'BAM', currencyCode: 'KM', rate: 1.70 },
    BW: { name: 'Botswana', language: 'English', languageCode: 'en', currency: 'BWP', currencyCode: 'P', rate: 10.57 },
    BR: { name: 'Brazil', language: 'Portuguese', languageCode: 'pt', currency: 'BRL', currencyCode: 'R$', rate: 5.34 },
    BN: { name: 'Brunei', language: 'Malay', languageCode: 'ms', currency: 'BND', currencyCode: 'BND$', rate: 1.35 },
    BG: { name: 'Bulgaria', language: 'Bulgarian', languageCode: 'bg', currency: 'BGN', currencyCode: 'лв', rate: 1.62 },
    BF: { name: 'Burkina Faso', language: 'French', languageCode: 'fr', currency: 'XOF', currencyCode: 'CFA', rate: 577.93 },
    BI: { name: 'Burundi', language: 'Kirundi', languageCode: 'rn', currency: 'BIF', currencyCode: 'FBu', rate: 1999.50 },
    KH: { name: 'Cambodia', language: 'Khmer', languageCode: 'km', currency: 'KHR', currencyCode: '៛', rate: 4070.20 },
    CM: { name: 'Cameroon', language: 'French', languageCode: 'fr', currency: 'XAF', currencyCode: 'FCFA', rate: 556.23 },
    CA: { name: 'Canada', language: 'English', languageCode: 'en', currency: 'CAD', currencyCode: 'CAD$', rate: 1.24 },
    CV: { name: 'Cape Verde', language: 'Portuguese', languageCode: 'pt', currency: 'CVE', currencyCode: 'Esc', rate: 109.35 },
    KY: { name: 'Cayman Islands', language: 'English', languageCode: 'en', currency: 'KYD', currencyCode: 'KYD$', rate: 0.83 },
    CF: { name: 'Central African Republic', language: 'French', languageCode: 'fr', currency: 'XAF', currencyCode: 'FCFA', rate: 556.23 },
    TD: { name: 'Chad', language: 'French', languageCode: 'fr', currency: 'XAF', currencyCode: 'FCFA', rate: 556.23 },
    CL: { name: 'Chile', language: 'Spanish', languageCode: 'es', currency: 'CLP', currencyCode: 'CLP$', rate: 815.44 },
    CN: { name: 'China', language: 'Mandarin', languageCode: 'zh', currency: 'CNY', currencyCode: '¥', rate: 6.40 },
    CO: { name: 'Colombia', language: 'Spanish', languageCode: 'es', currency: 'COP', currencyCode: 'COP$', rate: 4045.65 },
    KM: { name: 'Comoros', language: 'Comorian', languageCode: 'swb', currency: 'KMF', currencyCode: 'CF', rate: 420.00 },
    CG: { name: 'Congo', language: 'French', languageCode: 'fr', currency: 'XAF', currencyCode: 'FCFA', rate: 556.23 },
    // CR: { name: 'Costa Rica', language: 'Spanish', languageCode: 'es', currency: 'CRC', currencyCode: '₡', rate: 622.00 },
    HR: { name: 'Croatia', language: 'Croatian', languageCode: 'hr', currency: 'HRK', currencyCode: 'kn', rate: 6.22 },
    CU: { name: 'Cuba', language: 'Spanish', languageCode: 'es', currency: 'CUP', currencyCode: '$', rate: 1 },
    CY: { name: 'Cyprus', language: 'Greek', languageCode: 'el', currency: 'EUR', currencyCode: '€', rate: 0.82 },
    CZ: { name: 'Czechia', language: 'Czech', languageCode: 'cs', currency: 'CZK', currencyCode: 'Kč', rate: 21.41 },
    DK: { name: 'Denmark', language: 'Danish', languageCode: 'da', currency: 'DKK', currencyCode: 'kr.', rate: 6.12 },
    DJ: { name: 'Djibouti', language: 'French', languageCode: 'fr', currency: 'DJF', currencyCode: 'Fdj', rate: 178.00 },
    DM: { name: 'Dominica', language: 'English', languageCode: 'en', currency: 'XCD', currencyCode: 'XCD$', rate: 2.70 },
    DO: { name: 'Dominican Republic', language: 'Spanish', languageCode: 'es', currency: 'DOP', currencyCode: 'RD$', rate: 57.24 },
    EC: { name: 'Ecuador', language: 'Spanish', languageCode: 'es', currency: 'USD', currencyCode: '$', rate: 1 },
    EG: { name: 'Egypt', language: 'Arabic', languageCode: 'ar', currency: 'EGP', currencyCode: 'E£', rate: 15.71 },
    SV: { name: 'El Salvador', language: 'Spanish', languageCode: 'es', currency: 'USD', currencyCode: '$', rate: 1 },
    GQ: { name: 'Equatorial Guinea', language: 'Spanish', languageCode: 'es', currency: 'XAF', currencyCode: 'FCFA', rate: 556.23 },
    ER: { name: 'Eritrea', language: 'Tigrinya', languageCode: 'ti', currency: 'ERN', currencyCode: 'Nfk', rate: 15.00 },
    EE: { name: 'Estonia', language: 'Estonian', languageCode: 'et', currency: 'EUR', currencyCode: '€', rate: 0.82 },
    // SZ: { name: 'Eswatini', language: 'Swazi', languageCode: 'ss', currency: 'SZL', currencyCode: 'E', rate: 13.60 },
    ET: { name: 'Ethiopia', language: 'Amharic', languageCode: 'am', currency: 'ETB', currencyCode: 'Br', rate: 41.95 },
    FJ: { name: 'Fiji', language: 'Fijian', languageCode: 'fj', currency: 'FJD', currencyCode: 'FJD$', rate: 2.06 },
    FI: { name: 'Finland', language: 'Finnish', languageCode: 'fi', currency: 'EUR', currencyCode: '€', rate: 0.82 },
    FR: { name: 'France', language: 'French', languageCode: 'fr', currency: 'EUR', currencyCode: '€', rate: 0.82 },
    GA: { name: 'Gabon', language: 'French', languageCode: 'fr', currency: 'XAF', currencyCode: 'FCFA', rate: 556.23 },
    GM: { name: 'Gambia', language: 'English', languageCode: 'en', currency: 'GMD', currencyCode: 'D', rate: 51.55 },
    GE: { name: 'Georgia', language: 'Georgian', languageCode: 'ka', currency: 'GEL', currencyCode: 'ლ', rate: 3.21 },
    DE: { name: 'Germany', language: 'German', languageCode: 'de', currency: 'EUR', currencyCode: '€', rate: 0.82 },
    GH: { name: 'Ghana', language: 'English', languageCode: 'en', currency: 'GHS', currencyCode: 'GH₵', rate: 5.80 },
    GR: { name: 'Greece', language: 'Greek', languageCode: 'el', currency: 'EUR', currencyCode: '€', rate: 0.82 },
    GD: { name: 'Grenada', language: 'English', languageCode: 'en', currency: 'XCD', currencyCode: 'XCD$', rate: 2.70 },
    GU: { name: 'Guam', language: 'English', languageCode: 'en', currency: 'USD', currencyCode: '$', rate: 1 },
    GT: { name: 'Guatemala', language: 'Spanish', languageCode: 'es', currency: 'GTQ', currencyCode: 'Q', rate: 7.73 },
    GN: { name: 'Guinea', language: 'French', languageCode: 'fr', currency: 'GNF', currencyCode: 'FG', rate: 10032.55 },
    GW: { name: 'Guinea-Bissau', language: 'Portuguese', languageCode: 'pt', currency: 'XOF', currencyCode: 'CFA', rate: 577.93 },
    GY: { name: 'Guyana', language: 'English', languageCode: 'en', currency: 'GYD', currencyCode: 'GY$', rate: 209.10 },
    HT: { name: 'Haiti', language: 'French', languageCode: 'fr', currency: 'HTG', currencyCode: 'G', rate: 79.95 },
    HN: { name: 'Honduras', language: 'Spanish', languageCode: 'es', currency: 'HNL', currencyCode: 'L', rate: 24.00 },
    HU: { name: 'Hungary', language: 'Hungarian', languageCode: 'hu', currency: 'HUF', currencyCode: 'Ft', rate: 292.53 },
    IS: { name: 'Iceland', language: 'Icelandic', languageCode: 'is', currency: 'ISK', currencyCode: 'kr', rate: 123.11 },
    IN: { name: 'India', language: 'Hindi', languageCode: 'hi', currency: 'INR', currencyCode: '₹', rate: 74.77 },
    ID: { name: 'Indonesia', language: 'Indonesian', languageCode: 'id', currency: 'IDR', currencyCode: 'Rp', rate: 14224.80 },
    IR: { name: 'Iran', language: 'Persian', languageCode: 'fa', currency: 'IRR', currencyCode: '﷼', rate: 42105.00 },
    IQ: { name: 'Iraq', language: 'Arabic', languageCode: 'ar', currency: 'IQD', currencyCode: 'ع.د', rate: 1458.50 },
    IE: { name: 'Ireland', language: 'Irish', languageCode: 'ga', currency: 'EUR', currencyCode: '€', rate: 0.82 },
    IL: { name: 'Israel', language: 'Hebrew', languageCode: 'he', currency: 'ILS', currencyCode: '₪', rate: 3.24 },
    IT: { name: 'Italy', language: 'Italian', languageCode: 'it', currency: 'EUR', currencyCode: '€', rate: 0.82 },
    CI: { name: 'Ivory Coast', language: 'French', languageCode: 'fr', currency: 'XOF', currencyCode: 'CFA', rate: 577.93 },
    JM: { name: 'Jamaica', language: 'English', languageCode: 'en', currency: 'JMD', currencyCode: 'J$', rate: 154.17 },
    JP: { name: 'Japan', language: 'Japanese', languageCode: 'ja', currency: 'JPY', currencyCode: '¥', rate: 109.45 },
    JO: { name: 'Jordan', language: 'Arabic', languageCode: 'ar', currency: 'JOD', currencyCode: 'د.ا', rate: 0.71 },
    KZ: { name: 'Kazakhstan', language: 'Kazakh', languageCode: 'kk', currency: 'KZT', currencyCode: '₸', rate: 424.80 },
    KE: { name: 'Kenya', language: 'Swahili', languageCode: 'sw', currency: 'KES', currencyCode: 'KSh', rate: 108.55 },
    KI: { name: 'Kiribati', language: 'English', languageCode: 'en', currency: 'AUD', currencyCode: 'AUD$', rate: 1.31 },
    KW: { name: 'Kuwait', language: 'Arabic', languageCode: 'ar', currency: 'KWD', currencyCode: 'د.ك', rate: 0.30 },
    KG: { name: 'Kyrgyzstan', language: 'Kyrgyz', languageCode: 'ky', currency: 'KGS', currencyCode: 'с', rate: 84.80 },
    LA: { name: 'Laos', language: 'Lao', languageCode: 'lo', currency: 'LAK', currencyCode: '₭', rate: 9410.00 },
    LV: { name: 'Latvia', language: 'Latvian', languageCode: 'lv', currency: 'EUR', currencyCode: '€', rate: 0.82 },
    LB: { name: 'Lebanon', language: 'Arabic', languageCode: 'ar', currency: 'LBP', currencyCode: 'ل.ل', rate: 1507.50 },
    LS: { name: 'Lesotho', language: 'Sesotho', languageCode: 'st', currency: 'LSL', currencyCode: 'L', rate: 13.60 },
    LR: { name: 'Liberia', language: 'English', languageCode: 'en', currency: 'LRD', currencyCode: 'L$', rate: 171.47 },
    LY: { name: 'Libya', language: 'Arabic', languageCode: 'ar', currency: 'LYD', currencyCode: 'ل.د', rate: 4.55 },
    LI: { name: 'Liechtenstein', language: 'German', languageCode: 'de', currency: 'CHF', currencyCode: 'CHF', rate: 0.92 },
    LT: { name: 'Lithuania', language: 'Lithuanian', languageCode: 'lt', currency: 'EUR', currencyCode: '€', rate: 0.82 },
    LU: { name: 'Luxembourg', language: 'Luxembourgish', languageCode: 'lb', currency: 'EUR', currencyCode: '€', rate: 0.82 },
    MG: { name: 'Madagascar', language: 'Malagasy', languageCode: 'mg', currency: 'MGA', currencyCode: 'Ar', rate: 4125.00 },
    MW: { name: 'Malawi', language: 'Chichewa', languageCode: 'ny', currency: 'MWK', currencyCode: 'MK', rate: 794.50 },
    MY: { name: 'Malaysia', language: 'Malay', languageCode: 'ms', currency: 'MYR', currencyCode: 'RM', rate: 4.12 },
    MV: { name: 'Maldives', language: 'Dhivehi', languageCode: 'dv', currency: 'MVR', currencyCode: 'ރ.', rate: 15.30 },
    ML: { name: 'Mali', language: 'French', languageCode: 'fr', currency: 'XOF', currencyCode: 'CFA', rate: 577.93 },
    MT: { name: 'Malta', language: 'Maltese', languageCode: 'mt', currency: 'EUR', currencyCode: '€', rate: 0.82 },
    MH: { name: 'Marshall Islands', language: 'Marshallese', languageCode: 'mh', currency: 'USD', currencyCode: '$', rate: 1 },
    MR: { name: 'Mauritania', language: 'Arabic', languageCode: 'ar', currency: 'MRO', currencyCode: 'UM', rate: 357.00 },
    MU: { name: 'Mauritius', language: 'English', languageCode: 'en', currency: 'MUR', currencyCode: '₨', rate: 44.70 },
    MX: { name: 'Mexico', language: 'Spanish', languageCode: 'es', currency: 'MXN', currencyCode: '$', rate: 19.94 },
    FM: { name: 'Micronesia', language: 'English', languageCode: 'en', currency: 'USD', currencyCode: '$', rate: 1 },
    MD: { name: 'Moldova', language: 'Romanian', languageCode: 'ro', currency: 'MDL', currencyCode: 'L', rate: 17.61 },
    MC: { name: 'Monaco', language: 'French', languageCode: 'fr', currency: 'EUR', currencyCode: '€', rate: 0.82 },
    MN: { name: 'Mongolia', language: 'Mongolian', languageCode: 'mn', currency: 'MNT', currencyCode: '₮', rate: 2850.00 },
    ME: { name: 'Montenegro', language: 'Montenegrin', languageCode: 'srp', currency: 'EUR', currencyCode: '€', rate: 0.82 },
    MS: { name: 'Montserrat', language: 'English', languageCode: 'en', currency: 'XCD', currencyCode: 'XCD$', rate: 2.70 },
    MA: { name: 'Morocco', language: 'Arabic', languageCode: 'ar', currency: 'MAD', currencyCode: 'د.م.', rate: 9.18 },
    MZ: { name: 'Mozambique', language: 'Portuguese', languageCode: 'pt', currency: 'MZN', currencyCode: 'MT', rate: 62.27 },
    MM: { name: 'Myanmar', language: 'Burmese', languageCode: 'my', currency: 'MMK', currencyCode: 'K', rate: 1580.00 },
    NA: { name: 'Namibia', language: 'English', languageCode: 'en', currency: 'NAD', currencyCode: 'N$', rate: 13.60 },
    NR: { name: 'Nauru', language: 'Nauruan', languageCode: 'na', currency: 'AUD', currencyCode: 'AUD$', rate: 1.31 },
    NP: { name: 'Nepal', language: 'Nepali', languageCode: 'ne', currency: 'NPR', currencyCode: 'रू', rate: 121.35 },
    NL: { name: 'Netherlands', language: 'Dutch', languageCode: 'nl', currency: 'EUR', currencyCode: '€', rate: 0.82 },
    NC: { name: 'New Caledonia', language: 'French', languageCode: 'fr', currency: 'XPF', currencyCode: 'CFP', rate: 105.00 },
    NZ: { name: 'New Zealand', language: 'English', languageCode: 'en', currency: 'NZD', currencyCode: 'NZD$', rate: 1.41 },
    // NI: { name: 'Nicaragua', language: 'Spanish', languageCode: 'es', currency: 'NIO', currencyCode: 'C$', rate: 35.63 },
    NE: { name: 'Niger', language: 'French', languageCode: 'fr', currency: 'XOF', currencyCode: 'CFA', rate: 577.93 },
    NG: { name: 'Nigeria', language: 'English', languageCode: 'en', currency: 'NGN', currencyCode: '₦', rate: 413.00 },
    NU: { name: 'Niue', language: 'Niuean', languageCode: 'niu', currency: 'NZD', currencyCode: 'NZD$', rate: 1.41 },
    KP: { name: 'North Korea', language: 'Korean', languageCode: 'ko', currency: 'KPW', currencyCode: '₩', rate: 900.00 },
    MK: { name: 'North Macedonia', language: 'Macedonian', languageCode: 'mk', currency: 'MKD', currencyCode: 'ден', rate: 51.69 },
    MP: { name: 'Northern Mariana Islands', language: 'Chamorro', languageCode: 'ch', currency: 'USD', currencyCode: '$', rate: 1 },
    NO: { name: 'Norway', language: 'Norwegian', languageCode: 'no', currency: 'NOK', currencyCode: 'kr', rate: 8.88 },
    OM: { name: 'Oman', language: 'Arabic', languageCode: 'ar', currency: 'OMR', currencyCode: 'ر.ع.', rate: 0.38 },
    PK: { name: 'Pakistan', language: 'Urdu', languageCode: 'ur', currency: 'PKR', currencyCode: 'Rs', rate: 195.95 },
    PW: { name: 'Palau', language: 'Palauan', languageCode: 'pau', currency: 'USD', currencyCode: '$', rate: 1 },
    PS: { name: 'Palestine', language: 'Arabic', languageCode: 'ar', currency: 'ILS', currencyCode: '₪', rate: 3.28 },
    PA: { name: 'Panama', language: 'Spanish', languageCode: 'es', currency: 'PAB', currencyCode: 'B/.', rate: 1 },
    PG: { name: 'Papua New Guinea', language: 'English', languageCode: 'en', currency: 'PGK', currencyCode: 'K', rate: 3.52 },
    PY: { name: 'Paraguay', language: 'Spanish', languageCode: 'es', currency: 'PYG', currencyCode: '₲', rate: 7226.27 },
    PE: { name: 'Peru', language: 'Spanish', languageCode: 'es', currency: 'PEN', currencyCode: 'S/.', rate: 3.90 },
    PH: { name: 'Philippines', language: 'Filipino', languageCode: 'fil', currency: 'PHP', currencyCode: '₱', rate: 47.82 },
    PN: { name: 'Pitcairn', language: 'English', languageCode: 'en', currency: 'NZD', currencyCode: 'NZD$', rate: 1.41 },
    PL: { name: 'Poland', language: 'Polish', languageCode: 'pl', currency: 'PLN', currencyCode: 'zł', rate: 3.89 },
    PT: { name: 'Portugal', language: 'Portuguese', languageCode: 'pt', currency: 'EUR', currencyCode: '€', rate: 0.82 },
    PR: { name: 'Puerto Rico', language: 'Spanish', languageCode: 'es', currency: 'USD', currencyCode: '$', rate: 1 },
    QA: { name: 'Qatar', language: 'Arabic', languageCode: 'ar', currency: 'QAR', currencyCode: 'ر.ق', rate: 3.64 },
    RE: { name: 'Réunion', language: 'French', languageCode: 'fr', currency: 'EUR', currencyCode: '€', rate: 0.82 },
    RO: { name: 'Romania', language: 'Romanian', languageCode: 'ro', currency: 'RON', currencyCode: 'lei', rate: 4.21 },
    RU: { name: 'Russia', language: 'Russian', languageCode: 'ru', currency: 'RUB', currencyCode: '₽', rate: 73.68 },
    RW: { name: 'Rwanda', language: 'Kinyarwanda', languageCode: 'rw', currency: 'RWF', currencyCode: 'RF', rate: 995.75 },
    BL: { name: 'Saint Barthélemy', language: 'French', languageCode: 'fr', currency: 'EUR', currencyCode: '€', rate: 0.82 },
    SH: { name: 'Saint Helena', language: 'English', languageCode: 'en', currency: 'SHP', currencyCode: '£', rate: 0.72 },
    KN: { name: 'Saint Kitts and Nevis', language: 'English', languageCode: 'en', currency: 'XCD', currencyCode: 'XCD$', rate: 2.70 },
    LC: { name: 'Saint Lucia', language: 'English', languageCode: 'en', currency: 'XCD', currencyCode: 'XCD$', rate: 2.70 },
    MF: { name: 'Saint Martin', language: 'French', languageCode: 'fr', currency: 'EUR', currencyCode: '€', rate: 0.82 },
    PM: { name: 'Saint Pierre and Miquelon', language: 'French', languageCode: 'fr', currency: 'EUR', currencyCode: '€', rate: 0.82 },
    WS: { name: 'Samoa', language: 'Samoan', languageCode: 'sm', currency: 'WST', currencyCode: 'WS$', rate: 2.51 },
    SM: { name: 'San Marino', language: 'Italian', languageCode: 'it', currency: 'EUR', currencyCode: '€', rate: 0.82 },
    ST: { name: 'São Tomé and Príncipe', language: 'Portuguese', languageCode: 'pt', currency: 'STN', currencyCode: 'Db', rate: 19.06 },
    SA: { name: 'Saudi Arabia', language: 'Arabic', languageCode: 'ar', currency: 'SAR', currencyCode: 'ر.س', rate: 3.75 },
    SN: { name: 'Senegal', language: 'French', languageCode: 'fr', currency: 'XOF', currencyCode: 'CFA', rate: 577.93 },
    RS: { name: 'Serbia', language: 'Serbian', languageCode: 'sr', currency: 'RSD', currencyCode: 'din', rate: 103.77 },
    SC: { name: 'Seychelles', language: 'Seychellois Creole', languageCode: 'crs', currency: 'SCR', currencyCode: 'SR', rate: 16.52 },
    SL: { name: 'Sierra Leone', language: 'English', languageCode: 'en', currency: 'SLL', currencyCode: 'Le', rate: 10497.50 },
    SG: { name: 'Singapore', language: 'English', languageCode: 'en', currency: 'SGD', currencyCode: 'SGD$', rate: 1.35 },
    SX: { name: 'Sint Maarten', language: 'Dutch', languageCode: 'nl', currency: 'ANG', currencyCode: 'ƒ', rate: 1.79 },
    SK: { name: 'Slovakia', language: 'Slovak', languageCode: 'sk', currency: 'EUR', currencyCode: '€', rate: 0.82 },
    SI: { name: 'Slovenia', language: 'Slovenian', languageCode: 'sl', currency: 'EUR', currencyCode: '€', rate: 0.82 },
    // SB: { name: 'Solomon Islands', language: 'English', languageCode: 'en', currency: 'SBD', currencyCode: 'SI$', rate: 8.02 },
    SO: { name: 'Somalia', language: 'Somali', languageCode: 'so', currency: 'SOS', currencyCode: 'Sh', rate: 582.38 },
    ZA: { name: 'South Africa', language: 'Zulu', languageCode: 'zu', currency: 'ZAR', currencyCode: 'R', rate: 14.18 },
    GS: { name: 'South Georgia and the South Sandwich Islands', language: 'English', languageCode: 'en', currency: 'GBP', currencyCode: '£', rate: 0.72 },
    // SS: { name: 'South Sudan', language: 'English', languageCode: 'en', currency: 'SSP', currencyCode: 'SS£', rate: 177.76 },
    ES: { name: 'Spain', language: 'Spanish', languageCode: 'es', currency: 'EUR', currencyCode: '€', rate: 0.82 },
    LK: { name: 'Sri Lanka', language: 'Sinhala', languageCode: 'si', currency: 'LKR', currencyCode: 'Rs', rate: 199.48 },
    SD: { name: 'Sudan', language: 'Arabic', languageCode: 'ar', currency: 'SDG', currencyCode: 'SDG', rate: 55.32 },
    SR: { name: 'Suriname', language: 'Dutch', languageCode: 'nl', currency: 'SRD', currencyCode: 'SRD', rate: 22.15 },
    SJ: { name: 'Svalbard and Jan Mayen', language: 'Norwegian', languageCode: 'no', currency: 'NOK', currencyCode: 'kr', rate: 8.88 },
    SZ: { name: 'Swaziland', language: 'Swazi', languageCode: 'ss', currency: 'SZL', currencyCode: 'E', rate: 14.18 },
    SE: { name: 'Sweden', language: 'Swedish', languageCode: 'sv', currency: 'SEK', currencyCode: 'kr', rate: 8.74 },
    CH: { name: 'Switzerland', language: 'German', languageCode: 'de', currency: 'CHF', currencyCode: 'CHF', rate: 0.90 },
    SY: { name: 'Syria', language: 'Arabic', languageCode: 'ar', currency: 'SYP', currencyCode: '£S', rate: 1271.69 },
    TW: { name: 'Taiwan', language: 'Chinese', languageCode: 'zh', currency: 'TWD', currencyCode: 'NT$', rate: 28.11 },
    TJ: { name: 'Tajikistan', language: 'Tajik', languageCode: 'tg', currency: 'TJS', currencyCode: 'TJS', rate: 11.46 },
    TZ: { name: 'Tanzania', language: 'Swahili', languageCode: 'sw', currency: 'TZS', currencyCode: 'TSh', rate: 2188.97 },
    TH: { name: 'Thailand', language: 'Thai', languageCode: 'th', currency: 'THB', currencyCode: '฿', rate: 33.33 },
    TL: { name: 'Timor-Leste', language: 'Portuguese', languageCode: 'pt', currency: 'USD', currencyCode: '$', rate: 1 },
    TG: { name: 'Togo', language: 'French', languageCode: 'fr', currency: 'XOF', currencyCode: 'CFA', rate: 577.93 },
    TK: { name: 'Tokelau', language: 'Tokelauan', languageCode: 'tkl', currency: 'NZD', currencyCode: 'NZD$', rate: 1.41 },
    TO: { name: 'Tonga', language: 'Tongan', languageCode: 'to', currency: 'TOP', currencyCode: 'T$', rate: 2.24 },
    TT: { name: 'Trinidad and Tobago', language: 'English', languageCode: 'en', currency: 'TTD', currencyCode: 'TT$', rate: 6.79 },
    TN: { name: 'Tunisia', language: 'Arabic', languageCode: 'ar', currency: 'TND', currencyCode: 'د.ت', rate: 2.72 },
    TR: { name: 'Turkey', language: 'Turkish', languageCode: 'tr', currency: 'TRY', currencyCode: '₺', rate: 13.60 },
    TM: { name: 'Turkmenistan', language: 'Turkmen', languageCode: 'tk', currency: 'TMT', currencyCode: 'TMT', rate: 3.51 },
    TC: { name: 'Turks and Caicos Islands', language: 'English', languageCode: 'en', currency: 'USD', currencyCode: '$', rate: 1 },
    TV: { name: 'Tuvalu', language: 'Tuvaluan', languageCode: 'tvl', currency: 'AUD', currencyCode: 'A$', rate: 1.43 },
    UG: { name: 'Uganda', language: 'Swahili', languageCode: 'sw', currency: 'UGX', currencyCode: 'USh', rate: 4063.22 },
    UA: { name: 'Ukraine', language: 'Ukrainian', languageCode: 'uk', currency: 'UAH', currencyCode: '₴', rate: 27.67 },
    AE: { name: 'United Arab Emirates', language: 'Arabic', languageCode: 'ar', currency: 'AED', currencyCode: 'د.إ', rate: 3.67 },
    GB: { name: 'United Kingdom', language: 'English', languageCode: 'en', currency: 'GBP', currencyCode: '£', rate: 0.72 },
    US: { name: 'United States', language: 'English', languageCode: 'en', currency: 'USD', currencyCode: '$', rate: 1 },
    UM: { name: 'United States Minor Outlying Islands', language: 'English', languageCode: 'en', currency: 'USD', currencyCode: '$', rate: 1 },
    UY: { name: 'Uruguay', language: 'Spanish', languageCode: 'es', currency: 'UYU', currencyCode: '$U', rate: 43.59 },
    UZ: { name: 'Uzbekistan', language: 'Uzbek', languageCode: 'uz', currency: 'UZS', currencyCode: 'UZS', rate: 10974.69 },
    VU: { name: 'Vanuatu', language: 'Bislama', languageCode: 'bi', currency: 'VUV', currencyCode: 'VT', rate: 112.73 },
    VE: { name: 'Venezuela', language: 'Spanish', languageCode: 'es', currency: 'VES', currencyCode: 'Bs.', rate: 4200562.41 },
    VN: { name: 'Vietnam', language: 'Vietnamese', languageCode: 'vi', currency: 'VND', currencyCode: '₫', rate: 23193.45 },
    VG: { name: 'Virgin Islands (British)', language: 'English', languageCode: 'en', currency: 'USD', currencyCode: '$', rate: 1 },
    VI: { name: 'Virgin Islands (US)', language: 'English', languageCode: 'en', currency: 'USD', currencyCode: '$', rate: 1 },
    WF: { name: 'Wallis and Futuna', language: 'French', languageCode: 'fr', currency: 'XPF', currencyCode: 'CFP', rate: 97.86 },
    EH: { name: 'Western Sahara', language: 'Arabic', languageCode: 'ar', currency: 'MAD', currencyCode: 'د.م.', rate: 8.91 },
    YE: { name: 'Yemen', language: 'Arabic', languageCode: 'ar', currency: 'YER', currencyCode: '﷼', rate: 250.30 },
    ZM: { name: 'Zambia', language: 'English', languageCode: 'en', currency: 'ZMW', currencyCode: 'ZK', rate: 23.95 }
    // ZW: { name: 'Zimbabwe', language: 'English', languageCode: 'en', currency: 'USD', currencyCode: '$', rate: 1 }
};

export default CountryData;